# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 11:11
from __future__ import unicode_literals

import apps.exhibitions.models
import apps.photos.models
from django.db import migrations, models
import django.db.models.deletion
import libs.ckeditor.fields
import libs.slugify.fields
import libs.unique_boolean.fields
import url_tracker.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique_for_year='start_date')),
                ('description', libs.ckeditor.fields.CKEditorField(blank=True, verbose_name='Press Release')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('slug', libs.slugify.fields.SlugifyField(max_length=251, populate_from=('get_year', 'name'), slug_template='{}/{}', unique=True)),
                ('current', libs.unique_boolean.fields.UniqueBooleanField(default=True, help_text='Set the exhibition as the current show. Will appear on homepage')),
                ('extra_info', libs.ckeditor.fields.CKEditorField(blank=True, help_text='Only shows up on homepage, below exhibition picture andname, if it is current', verbose_name='Extra Info')),
                ('press_release_photo', models.ImageField(blank=True, height_field='press_release_photo_height', help_text='Used if it is the current exhibition, on the homepage. If not specified will use first of the uploaded photos on the homepage', null=True, upload_to=apps.exhibitions.models.image_path, width_field='press_release_photo_width')),
                ('press_release_photo_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('press_release_photo_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('artists', models.ManyToManyField(blank=True, related_name='exhibitions', to='artists.Artist')),
            ],
            options={
                'ordering': ['-start_date'],
            },
            bases=(url_tracker.mixins.URLTrackingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExhibitionPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400)),
                ('caption', models.TextField(blank=True, verbose_name='Extra Text')),
                ('image', models.ImageField(max_length=1000, upload_to=apps.photos.models.original_image_path_function, verbose_name='Image File')),
                ('thumbnail_image', models.ImageField(blank=True, editable=False, height_field='thumbnail_image_height', max_length=1000, null=True, upload_to=apps.photos.models.thumbnail_image_path_function, width_field='thumbnail_image_width')),
                ('large_image', models.ImageField(blank=True, editable=False, height_field='large_image_height', max_length=1000, null=True, upload_to=apps.photos.models.large_image_path_function, width_field='large_image_width')),
                ('thumbnail_image_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('thumbnail_image_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('large_image_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('large_image_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='')),
                ('date', models.CharField(blank=True, max_length=100)),
                ('medium', models.CharField(blank=True, max_length=100)),
                ('height', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Height (in)')),
                ('width', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Width (in)')),
                ('depth', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Depth (in)')),
                ('dimensions_text', models.CharField(blank=True, help_text='Only use if the seperate dimension fields do not apply to this piece.', max_length=300, verbose_name='Dimensions')),
                ('artist_text', models.CharField(blank=True, help_text='Only use if not solo artist in show', max_length=100, verbose_name='Artist')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='exhibitions.Exhibition')),
            ],
            options={
                'abstract': False,
                'ordering': ['position'],
            },
        ),
    ]
