# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0003_auto_20160108_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='current',
            field=models.BooleanField(default=False, help_text='Shows the current exhibition on the homepage'),
        ),
    ]
