# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 11:21
from __future__ import unicode_literals

import apps.photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0004_auto_20160108_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionphoto',
            name='vimeo_id',
            field=models.CharField(blank=True, help_text='\n        The part after <code>https://www.vimeo.com/</code>.\n        For example, the ID for <code>https://vimeo.com/45830194</code>\n        would be <code>45830194</code>.\n        ', max_length=400, verbose_name='Vimeo ID'),
        ),
        migrations.AddField(
            model_name='exhibitionphoto',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='\n        The part after <code>https://www.youtube.com/watch?v=</code>.\n        For example, the ID for <code>https://www.youtube.com/watch?v=2IWBHAZ9Q_s</code>\n        would be <code>2IWBHAZ9Q_s</code>.\n        ', max_length=400, verbose_name='YouTube ID'),
        ),
        migrations.AlterField(
            model_name='exhibitionphoto',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=apps.photos.models.original_image_path_function, verbose_name='Image File'),
        ),
    ]
