# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0005_auto_20160401_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionphoto',
            name='gfycat_id',
            field=models.CharField(blank=True, help_text='\n        The part after <code>https://gfycat.com/detail/</code>.\n        For example, the ID for <code>https://gfycat.com/detail/WarmSmartGeese?tagname=civil%20war&tvmode=0</code>\n        would be <code>WarmSmartGeese</code>.\n        ', max_length=400, verbose_name='Gfycat ID'),
        ),
    ]
