language: python
services:
  - redis-server
install:
  - pip install -qr requirements.txt --use-mirrors
before_script:
    pep8 . --exclude=migrations,static --ignore=E501
script:
  - python manage.py test

notifications:
  email: false
