language: python
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database django_canadanewyork;' -U postgres
- python manage.py 1>/dev/null # check that manage.py executes without error. if there is an error, will print traceback
- python manage.py collectstatic --noinput
script:
- python manage.py test tests --traceback
env:
  global:
  - DJANGO_SETTINGS_MODULE=configs.settings
  - CANADA_TESTRUNNER=True
  - CANADA_ALLOWED_HOST=*
  - CANADA_DEBUG=False
  - CANADA_DEBUG_TOOLBAR=False
  - CANADA_DEVSERVER=False
  - CANADA_SENTRY=False
  - CANADA_STORAGE=local
  - CANADA_CACHE=dummy
  - CANADA_CACHE_TEMPLATES=False
  - CANADA_CONSOLE_LOGGING_LEVEL=INFO
  - DATABASE_URL=postgres://postgres@localhost/django_canadanewyork
  - DJANGO_SETTINGS_MODULE=configs.settings
  - SECRET_KEY=not_so_secret
  - CANADA_QUEUE_ASYNC=False
deploy:
  provider: heroku
  strategy: git
  app: canada-development
  api_key:
    secure: KTw/uTcUc66zhxdbh6RwqEIeq4kHuSiy2RvF44f39Is1F0lR5Fs8U6mN2kfKOJjFl19tFHxmfc9JdJi+Z572Pit35rlS0q8dM6Ot1+qmj7cXJMZJfe2A5kB9AZyj1+df+w0vD3Bd0Dv/iyzUPUqR/YTXyMVGwvR/o+kQ3r1qWEc=
  run:
  - python manage.py syncdb --migrate
