language: python
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database django_canadanewyork;' -U postgres
- python manage.py collectstatic --noinput
script:
- python manage.py test tests --traceback
notifications:
  email: false
env:
  global:
  - DJANGO_SETTINGS_MODULE=configs.settings
  - CANADA_TESTRUNNER=True
  - CANADA_ALLOWED_HOST=*
  - CANADA_DEBUG=False
  - CANADA_DEBUG_TOOLBAR=False
  - CANADA_DEVSERVER=False
  - CANADA_SENTRY=False
  - CANADA_STORAGE=local
  - CANADA_CACHE=dummy
  - CANADA_CACHE_TEMPLATES=False
  - CANADA_CONSOLE_LOGGING_LEVEL=INFO
  - DATABASE_URL=postgres://postgres@localhost/django_canadanewyork
  - DJANGO_SETTINGS_MODULE=configs.settings
  - SECRET_KEY=not_so_secret
  - CANADA_QUEUE_ASYNC=False
deploy:
  provider: heroku
  app: canada-development
  api_key:
    secure: BUuAQT37AoOLTRfOoyw17OkJGydKkJe9IAOygXon56kiqzNJPTd/AspS2OQRNx3T8TU5qZW0Q8b4Bvtg7r1IlyvwrRfXN9p5PLO9MUVo3zmuYbR4aYK/gth45PqqCfr0g9ZIuEuzjvJZZSope35hLKiHbkS6+PsI/UOToDGatJw=
  run:
    - "python manage.py migrate"
    - "python manage.py collectstatic --noinput"
