language: python

services:
  - redis-server
  - memcached
  - postgresql

install:
  - sudo apt-get install -qq libmemcached-dev
  - pip install -r configs/requirements/prod.txt -r configs/requirements/testing.txt --use-mirrors -q

before_script:
  - psql -c 'create database django_canadanewyork;' -U postgres
  - DATABASE_URL='postgres://postgres@localhost/django_canadanewyork'
  - python manage.py wipe_storage

script:
  - python manage.py test

notifications:
  email: false

env:
  global:
    - secret:  "STNK4nGs4ib0AviClb+GPWQ7M22byLnYsSK9qy7tPvJdcwSwk3yj5oNANiWC\nJQrW6XFdWBqS+cr9HJU0wq61gMNipnaQ7JvDwX7Lx8isBwV2z86W0kK4Zlwf\n0Zf63vAWOtJJyXfXDGOGCWwf4fdPVBwTchnlTJh9kt/R21tQTYo="
    - secret:  "YFyx1NIdvyVUyyCBTQph8wJwqTVzvhRInALwdPYtb56eKlLPWmtuSv7i0gq7\n3zcXULuNrSfAvJEPhwb1WV+rZ0cWXi7nmP7J2mkzXpUsYuDHI7DL/L2gSZlI\ny7kL1c6G502hSBiw3Nyy61HvT3J09+j2pgZhaUzNBbncRMx0kq4="
    - secret:  "zLp84RDS1YKcf8FI2VZzg1Stik9EILsThue2vSR3Pf7lvj61kuXD9mxm3cEd\nAnZiGxPJOGUwB9CEl4OeUcLp+ir4bySMnwR7o77oyK2mLluSPqfMGcPXjeT5\nyf1nR81GQnQVeuOA7KfcOPi34eIQ+V++8iQWNOlkthUZZhx4Lg8="
    - secret:  "qcA8XTWd5dP7+c9cLvueFI97NHs29vQjpeSqJuE9uzLKXLH1BRFRsLG1gt/0\nPMkAmhqpcalotXDU6lTUwI+UWTXnShk+hS9k8TRZ+nwX84CLrduk7DYOd7x1\n3seobdNQn+xBc9QQb3MplythxtDp3g4B7l4IzjqV2ekpzZ1QTvs="
    - secret: "rQIaX/Wle8JHxqFthr9e9LeTfpw2BhD9B3zt1AMxj6ubnzmY5+esU9L/NQwx\nBFZD4ZfEyTSGX8F52KHFrrTwHe85fuLYWp7iP8YTle9bD5WZQLdzi9Xp0qY5\naukiYEvhge0oav/fw8WCuVa4f9BMSF+MqL/qVY2K1FBij4sfDQU="
    - ADMIN_USERNAME=saul
    - ADMIN_EMAIL=s.shanabrook@gmail.com
    - DATABASE_URL=postgres://postgres@localhost/django_canadanewyork
    - DJANGO_SETTINGS_MODULE=configs.settings.prod
    - AWS_BUCKET=assets-testing.canadanewyork.com
