language: python
before_script:
- psql -c 'create database django_canadanewyork;' -U postgres
- python manage.py validate
- python manage.py collectstatic --noinput
script:
- python manage.py test tests --traceback
env:
  global:
  - DJANGO_SETTINGS_MODULE=configs.settings
  - CANADA_ALLOWED_HOST=*
  - CANADA_DEBUG=False
  - CANADA_DEBUG_TOOLBAR=False
  - CANADA_DEVSERVER=False
  - CANADA_SENTRY=False
  - CANADA_STORAGE=local
  - CANADA_CACHE=dummy
  - CANADA_CACHE_TEMPLATES=False
  - CANADA_CONSOLE_LOGGING_LEVEL=INFO
  - DATABASE_URL=postgres://postgres@localhost/django_canadanewyork
  - DJANGO_SETTINGS_MODULE=configs.settings
  - SECRET_KEY=not_so_secret
  - CANADA_QUEUE_ASYNC=False
  - CANADA_DUMPER_LOG=False
  - CANADA_IMAGE_DIMENSION_FIELDS=True
