language: python

services:
  - redis-server
  - memcached

env:
  global:
    - "DJANGO_CONFIGURATION=TravisSettings"

install:
  - sudo apt-get install -qq libmemcached-dev
  - pip install -r configs/requirements/prod.txt -r configs/requirements/testing.txt pylibmc --use-mirrors

before_script:
    pep8 . --exclude=migrations,static --ignore=E501

script:
  - python manage.py test tests.apps

notifications:
  email: false
