language: python

services:
  - redis-server
  - memcached
  - postgresql

install:
  - sudo apt-get install -qq libmemcached-dev
  - pip install -r configs/requirements/travis.txt --use-mirrors -q

before_script:
  - psql -c 'create database django_canadanewyork;' -U postgres

script:
  - flake8 .
  - python manage.py test tests

after:
  - python manage.py wipe_storage

after_success:
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - git remote add heroku git@heroku.com:canada-development.git
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  - heroku keys:clear
  - yes | heroku keys:add
  - yes | git push heroku master

notifications:
  email: false

env:
  global:
    - secret: "gyfr2f6X5Tu9t5+4i40nB8d4T3VPElzszhK+z3q7wQEzsvfKRQdFZDj2CWif\n+FH56rtkDF6LZfk47pEIjKASAoTma2qxrZtV1PDGSbxk0Eo09ToLMuOsfsP2\nRPG74gLw+J/JPD90TTS5bqUqVOyGJvuDFKKi3UB5O4FisprfAKc="
    - secret: "wac1kCYd+cqjuRSZhzpqejMQgQWorJ1n5ErdsAoqLHENs3P9S9whGyI9TxK8\nAug1495OO8k2vDiwD3DcFbmHZeiSI6cBcEvxXLvseKC2y9BvYhwJm2dYbbsi\np3vYZp9tzPs46jnWWYTrAIuD9a5YYBFsMF9RY0OjdmWsWNf3T+I="
    - secret: "Ski5YykCbJ5SkqASnOhg7QTk5nqstyjglkfdx3+6hI1TA/Q9lOo8/TDu0yWJ\nElPq9v8wiP0NMnG0pNmfokWUCZ74lh/dt/X5JkskGjspVoNq98xd4Cnw+FAQ\nr5LlqqGRF3hG5CZ0O3TGEH8aY1EVBRfLw5n1++2ebA5ukBNxlUQ="
    - secret: "WE0fMLaiswICg2dibYF4yJDe3jA9LKiVWoC/9hxrfCMcCtZGryGYTdciPUPT\nAMNw5bo74l2W1OKzXxSVZxD7iZwkMDbR8WvK3ppq/UBCGhzNBMJib3Jn2OhA\nFAsZZtjWaAihGrCZpJFAHo0AX9Yx4KOxWP4YdVxrx/6C5DAa3PI="
    - secret: "BcDJbFBhqOS99VPDFkt+oE1C8pLhTnIa0e+ftueEGCPqLPmIJF+xsh0R6KCX\nOUg46mQHnImC39D77281p6VQoXDhpTGQTEzBbfZvlA/PdEEJ3HHKE3ChWqbT\n8qkqrD0q7+P21pcDcPESI2Q9xQ8OyCPXYaN6kDQTl+dak4c80lY="
    - ADMIN_USERNAME=saul
    - ADMIN_EMAIL=s.shanabrook@gmail.com
    - DATABASE_URL=postgres://postgres@localhost/django_canadanewyork
    - DJANGO_SETTINGS_MODULE=configs.settings.prod
    - AWS_BUCKET=assets-testing.canadanewyork.com
    - secret: "YVx9ndPE6IEVTal/LIZHGOWt3iVTx1QHdnSzwZXLg61ZPoi4NVP/hbpanvWC\nFp82KruErsVRx+7ST2UteRqRgMkJaf7BKQbub0IdMUxk118Vv0AEtfo0waNa\nl+icsE3idYYYugwkKcNloMrslT0lNSQZnL5vhoSQGDCr3Wwpndk="
