---
language: python
services:
- postgresql
install:
- export DATABASE_URL=postgres://postgres@localhost/django_canadanewyork
- export DJANGO_SETTINGS_MODULE=configs.settings.testing
- export AWS_BUCKET=assets-testing.canadanewyork.com
- sudo apt-get install -qq libmemcached-dev
- pip install -r configs/requirements/travis.txt --use-mirrors
before_script:
- psql -c 'create database django_canadanewyork;' -U postgres
script:
- nosetests --version
- nosetests --plugins
- nosetests --help
- python manage.py test
after-script:
- python manage.py wipe_storage
notifications:
  email: false
env:
  global:
  - secure: ! 'H5dKDlHQ/ioSjY3o7+90H6va9ELBKN2N+GKvZQFf+u69LwdJQGadBTG4qxN/

      ifTAulv+FMZTGhnSkBJE/RhamO/jlrI6swCjit7lQ8VWixXL7WHkt9KpTO6+

      T/YKK74Op9ccJhk91jRJHPS7ySRucz/5GEKkbIFg8ExeeXhQVJQ='
  - secure: ! 'Y/REF8wkRhzdlnUUKHP5rSqTDNdX7wufiiX8BbT7c46nWT/SRxSEYB5hKuKw

      7xtYVXr14qHfwQopKb3I1P3u64WKsEAPcjTd8rNugKR5leOteuvI7qbyukp2

      arT3yrISivf6HcllKbMBNC48MB48EhyR5wcAts4ysYIFywa+BHM='
  - secure: ! 'pQ9aSyCWu6EnnHEuLI6hNoMYk7YIbFtxI65oesk3cVxzmDeH6fTrH1WG8OmF

      l3nhQ1eFSZPBevGPljn2qzwKc0Okl1j0BuWt+UUPNyvKm8CPvTARYqF52+4r

      iFnJQh1lFsox3m0KjOmQt4SatdcNmqmaniXuGWO57OKrqoacjHM='
  - secure: ! 'C4aJCsLh8Ijuk3EmFi0c0uB6GIgmzmaQmZoSXD8x18DuPyxeoKA0962Gl38u

      rAqL8K0st5b2Y5lRQmx2yeYnVcWtyVlU31bbATS2Hff7NbV9BuhzO/0M+cNR

      rJtGwe4F6UxtpxOyh54lYcgJAxjYo491La3ueyHbTcI4OpSQ+kw='
  - secure: ! 'li2V7Jo4mJFYEXGZlBj8GigVO2YPJypLByUWOqwanH4SxkGgZOoh3v3GbCEu

      yt/KJBLznVr/njnkEJZuJpad2Uv3JW3WQ9pmoN0ehL/IS+U7zyHtkTKlKtiO

      DmbpzVR+4ohgg/7jMeEnIaPdKpz/B31nFjGNEBDE4yvnANPR6a8='
  - secure: ! 'sfXnzVDsMKXe4IWi6whuUDIIEkQ2kQU2CrVPBcJnrTD1V2PvlqRfVP446E0h

      NHhij+bQh/MDGs75Kguyh9CosYZDvrvyNOnnhSDXae+MhvOxK1mlVoZOwb9U

      gERC5rcpWDnxz54hgB4nzn/w9YUR3mZ/X4L005gsNO082yvJITw='
