language: python
services:
  - redis-server
  - memcached
install:
  - apt-get install libmemcached-dev
  - pip install -r configs/requirements/prod.txt -qr configs/requirements/testing.txt --use-mirrors
before_script:
    pep8 . --exclude=migrations,static --ignore=E501
script:
  - python manage.py test

notifications:
  email: false
