---
language: python
services:
- postgresql
install:
- export DATABASE_URL=postgres://postgres@localhost/django_canadanewyork
- export DJANGO_SETTINGS_MODULE=configs.settings.travis
- export AWS_BUCKET=assets-testing.canadanewyork.com
- export SENTRY_DSN=https://fa2324424bba43788e58f5e98af90dc3:240da78eed7a46a4998095d1b0157e0f@app.getsentry.com/2745
- sudo apt-get install -qq libmemcached-dev
- pip install -r configs/requirements/travis.txt --use-mirrors
before_script:
- psql -c 'create database django_canadanewyork;' -U postgres
- nosetests --version
script:
- python manage.py test
notifications:
  email: false
env:
  global:
  - secure: ! 'DBRah/ln+BEUhJXGUYESUrBQBlR0Nezcf/6j7VZ+BncBiAlWU6K31CnjzsDC

      QXAaptbf8lNKQGdfIHdi5N5R5WGVi61IfjpgU3OcboTSn21cTf6qhDiHBfIF

      GhZqcfS8vT5F5eDthScROlNOgHIMb84b5PuwuweodiLFMC/aBm0='
  - secure: ! 'p87Qrdm18T0R0PK+SvZkA/IsTxzzuxkk0CkJyX8L8pN/ghIxiq7ixOE8O4Tx

      YmBxSGFqVGTnFlJURpDYg/j59ZP1i3qRNWlZXK40J9kPEWg9HU9BkNdoYZfr

      d/jUR4kpnDgm/QwQEh0FcSutGujHxGkHKo4joeNPg1iQizHOz4I='
  - secure: ! 'BTTdQ+e2IY3V3nvpyCNaLFsvF1KZL7/fffIGT6Lu6bKTsH/GZRleoETWFuli

      kGOen6zvZA0QjpMjenPxf8TToyInTPPgmHO2D8qhYMIXavSyTuCe8gDjQ/KM

      G0w3TvSAK/WeEPzIQzIxkMb9j9j4auD2h2RSjEVgQKFGh7uM0DE='
  - secure: ! 'pM7agohUi9Nx0YkYnThZK+9vVywheP7awG+DxRkLyM+Kxbfjuxyb+nWtiFVp

      Yj+mxj8gYWgVpuFtPCaHVmDtaZU2T6MZ7paslu2qeop9K9jl18em6j842WsR

      vdY+Uc53PrqmcztIQd+nuTCp1J1iumH8PzrN+GiOmbhquyQRVTI='
  - secure: ! 'Ge8LxBIWl0C9L6UQlgpsm9T9C3bLbNrXUE43/9BQsgyHEK2nb0KdFmzD4yij

      coJ4DyiW/ppi3tSecPrLJqlncbZ/cGOORJYVJOrjPrpUfR+kNV/jYTjvv0XJ

      KT3fUoeVfTeouYnY6shxZGHHNmbrtVwsxzORZ8HL3hCaERo+2lE='
  - secure: ! 'eRft+KcqBtXMtf9NplkwJTd9L527iMnLkaY7S7hvLSBpAIy7l16mwH/DfsDp

      XpfVdRM8VQbpKIixSn8uEGcZG2UMu1C12VEEQrXrsZT4W8i8eSdOONolsBgw

      ZagtFAzzV7KtlRzSrsETACUcLmCrzWmiAHpGL6+C6SDrBGxPpBM='
  - secure: ! 'kkYkqe5CBDQV8776Hu7FNRo1skmuaxWXMvsT+qx3fjvsW/r9lKxnaa4oxbfc

      TV55eq0CrQx0wUxfIuJkj4yM/QaEt5e0dEKLU8bP/FTqXhfLhwi/O1CAFYvT

      w8CZUEUjW/nKcPXlS2onjTR7aK7pD0IujWrGPUGioNQL9AbHBPE='
  - secure: ! 'C2bcHqWrgJDgf2owWvLRVxj8MYFLCXTfAWnW+dLlbzSHUl32yy0CMkN3BtPa

      e88PRjHnSF828WAYsi3dCPYk/F7Re6YvGMbCUIDqZLA8nE8l6iOQ6Tg2ZtYa

      dhqhTKfPoWE82GQkScC/6ArYu0/IVFd9p7kd9okjvOgoWLMCAls='
  - secure: ! 'LQbOGaDraBqGgi70gHS4RuxO/AgDzd3zvS8qfc5P33khI6rCcBpdASM0tKj7

      S5Q3kEdXSqHSBXP1N2/R5I7UWiIZwZWSckXO7qhYPLiKbY9U7ixbhSTUP1hH

      UtvqUQ4sk6Sl7i8vG+a101bmimOxqu6MSeAZYXkw74eNe9qJpBg='
  - secure: ! 'P1h5nh5QILF9cbbqtq7TzraSrVKVf5TAvKi09fC4sHlHt7y/rg5X/R2WEE2F

      w+5K9KVXDr4iVUFb5a17DTSHMW0MgpvP/dl98n6uGWTjyweB8KRCNsL0Q815

      Ed3MClXyi1jVf4N7A9AEpcmXI4WfReHUpW8PXz0Uqzt9NFKJVU8='
  - secure: ! 'Ym9mdEchup4qBiiIIccdgtqMHB6dhHdUqHHBjJ+4/zVc9AdWqznedSVfhaF1

      y+8W8fRG0wz/6YzIdAdT0NWVWeKzKeG+yyU98bvK8vj0FFnqZsZPUYD2XjW7

      sVePcDDEe70gKsyamsnURpDLl5Ea6zGSO6UWS+MLxm/ZseU/iBI='
  - secure: ! 'FlQ+wFh+FCf0nbrdAaALa0uSNgMSsbW93gDgy5XtKeC1ZvnmXCpVRyMqPk/r

      FIweYvYSRLcAwfCCvlMuA0GAlz6tsn3HMaG0dIqSg6XakRG0/dNv7tnspNqT

      ekdWyBNHQQcWWyluWSkcfwXVW95XGUGOu/8wi7qIKu8FUkIJZ1k='
