---
language: python
services:
- postgresql
install:
- sudo apt-get install -qq libmemcached-dev
- pip install -r configs/requirements/travis.txt --use-mirrors
before_script:
- psql -c 'create database django_canadanewyork;' -U postgres
- nosetests --version
script:
- python manage.py test
notifications:
  email: false
env:
  global:
  - secure: ! 'EszIw/uE5iy958jpGYNOClGH+N6egs4k5oKXO+l/PxZYt556aBdz2ANlZN+f

      TwWjynZnsKLD6rLPo6kiZfar65V9jchSExqj44gLaEn9NYAFaHoooBfNfl/u

      ABQzosoTfkBXv4dhHt4HHmUbR56h7GQ2S1WLwlP2VSsPEavlWzc='
  - secure: ! 'ltf+zJgmNmYg6XHNN/9peurzW33VAJDpdNy65s3DyUIJe6DgrgHuMYG1NBne

      j+AsWLMpepiXMyekqndtH8sRmjEbQR93XMjXSHYkEAiurYUX3QUpG0nUiMzL

      6k/nQm7mt7EXsKI1hO7VZ7rLdeVK4suFO++pIHhdE/fRo5XufKE='
  - secure: ! 'V71+LKMecF5PzEqOWIYLcNFWcxqFeLI4G2dbBeDjmXDeUBQQcQACrDA3snZJ

      Xgt6+8MBL7n8lZSkmW5Ps3EYdAmp2yYaAa6KJxbw/FBwvAnFb7GdbMi17bLM

      qWkt8XDHSnaRcrtm5tgffjUQyAIvCAA9MRavLbewoYlRvN/vaNg='
  - secure: ! 'U/4QwgeC6F6ADzy2HP0NfYTj6WMvCS5nxP1xj9GS6fqFGhXm/Z8kA3h35Oku

      JontEjY9oodUhZ5CRHPKmVbUW9Zr0ZU1itoIs9A/p024L6fDRkSS3HXjjY51

      WR0OzFtgSlDgmU72P6/L+3XfBslJaLa+refovPiI5JIdBAx+odI='
  - secure: ! 'Mf68tO4j2LDpGJudPX+sBq5dT99TjTkf5EXHVy5tzbIiP+YcfLI5OltjPdGw

      TBtCvnjaR2e20Zj+ai8UN5HzP5ErOabdt53VGWBYJlROELLbYdH/Ajo9C19u

      29KrvGaxhr3J9fJrVAedXUi6fDGzH5RQIwqUtOoQung2O3bk1VA='
  - secure: ! 'f83tGNTckGVdleE/FCOsjEpkrGOXJZBULw9LlDrrIJ2QXE+1Fq7jB2A5O8eO

      5/tOFmZkrxbgAnt9mwv5V6NNK1MmxYXcOnLECVFOQkDxKsqpU6DDJEFm8xap

      MWyeFLUoUS/i2GLxiEcS6qrU5j12UfYrKqlkQxNdcWYbFzMWCng='
  - secure: ! 'gmTovw7/09Fwm7WgkTeIDeTfHA3fP56j4v2u//ropOhu/Umm/wddvGkhjDTR

      +F0xXWRjn2i/457VozPwfUbqMXfIblC+VdOHPolAbn7XCW9odkQD7FD4TyuH

      wLlKljDEZ5aDZqblhzt6WuVmKanNCFsUhYBtIRJM0GNVdlaxURo='
  - secure: ! 'QaEZHqviSizb8NZGyyU8OR2uBXoVXGT7818NfdxP0z9dZMnNvVZpjALvpVK8

      XSqCQCtjaU6j9HdOYJSDbs+k/0CzvcH0VbjlGYfTNt3/CC08eyoe0Uq8CMvI

      SVwL/nNP1OlEWgpS8OTn094hQve3NR/aRKk5CtqnNmJ/jDAXoZA='
  - secure: ! 'gY6Zo2vVA4nMP74QFC+5oBRa2A4RQFE1v8Lfxi3wEOSeSmEmHJ/CMJZ4tQmD

      bIeizrvj1r0UJbigY6JDUKVWXebxRNCZRNvyKpvFLYXvqcPYQcFZVPftUvX7

      APmyLbmIj8aRiC5DZq049c5Iop4EIT6ydOcgA3LGiW3KkzRuT04='
  - secure: ! 'dAchRuDKha8AgLkQHImMj/IzRoM8NneIoc61lKR+GoRXJM8+1qO35jpHiLKx

      b6pc2cPnM1z9LI4s8UIwlBau3r0uI7GPFqlUHr/jk3cs8aCfAeMxH+HQuuQb

      jdY2Cbwj1mPTIlmVrJRvgpBHn8MU9vi9HS8QLqbBPHa+lJIp1wk='
  - secure: ! 't348lUIAPoNMFa2FgChsw7meVGouOF4Ufo83fphE0K1pr1pI8J6ufGVgZhLO

      x0yxzil+k81HGxxbSmb/aCXFSun9pUroiQ3kCLopuA5MSX55wjJIO2dJwe7R

      bUaFXknztVC4Cz2jkm1voAtiYj+Po2Kg2WljO/GmjrHbztiA8Fc='
  - secure: ! 'zCu+TEpUWMbTIxleuzbSVjUItrkfEQKaodbQ4XLe4topr9hyQVXgMyTRDKvo

      gHDtt5tycLo96A5R4AXAL+WS7C+3t7nuTrmBYUhnanjJFa0mLX3x8ypkDdjy

      94/rkTV4B0PDhuKjMQKLJOLtambiqh9yIgGA54TwYmcmLeC/tW8='
  - secure: ! 'rTnC7unI9/VRJGSCHJqiEScaATdj79OrvIzEJR/pTQ2ZUKK1eAPr3FWAXnwk

      jwiugWVRmTs2ET2xqBC8c01GoVAXpxRFD/mWIdtx9biwYUJSTKoW+0MO8QxV

      mceaGs5/apwrEPwFP43qs8G2qLi+BdzdECd1WsmbFIc+HcUiGlQ='
  - secure: ! 'WrHAWGkKYhasbr2iMWHvb3I3fhMV64V4SerVTLvuRyjpKQgI7x7rOMCpTgzh

      vrAjtG100KDnnWBAXxsKCtFMU6R9mTBN8H06l8sAq7e+TDqTTeMXTk1Dy5Mq

      6wzSubMo7uHorihQmZwhotIDcQxHy3xnh/jzTbV3oQNzhhdfxuU='
  - secure: ! 'WQiXS8yPP8ThzERjKTv+5KsCKHUSYDst9c4U/P9IuMgTiKxGSHD9LJjZ2Swq

      04SOr72Y6hYhJss4s5m52wuH6DraLJN6/FLGXRRyDBZEfFGqxjwtzh2bF0cD

      75BVFcFEAQsySHx90crmzXqOQk5SluGTI/L+4vItpuNMP6Ts8rg='
