---
language: python
services:
- postgresql
install:
- sudo apt-get install -qq libmemcached-dev
- pip install -r configs/requirements/travis.txt --use-mirrors
before_script:
- psql -c 'create database django_canadanewyork;' -U postgres
- nosetests --version
script:
- python manage.py test
notifications:
  email: false
env:
  global:
  - secure: ! 'yxrFQmHPIl1v7jHk8+so4eiOIenbyB2puc/qv06qNbndAyYFKkLDNpkE46Jx

      0gXI1J6CXuqgt9uBZ8ko4juie1Q6IId+keH/9YVXoH1vHdoNa/9Wa0BZtjMH

      3UElLggacG4W04XS+WcXldZHHtaBMba571j6lKXjlxB5FBs8CGg='
  - secure: ! 'VfPDXZqm10wC5qbEfjuXSAnRlFbhJorrxGuSVtoSieElxWEJIL8FKoY+MatC

      eWD42mxB80jypR//oEDDAlwAW1yszdalCSCmND9q3druyZO0dwMSEG9itCHZ

      l0xEx1zX6CUvMGR4OLLawVAaubC6htH+7RfL92tweGzFUpI/eFY='
  - secure: ! 'BPViU0FatTzphDr1NQ2NEK06EGceGnwWFPVYXxiteC5jCf/Ff/Aic8ydpLso

      nsZGQsA2cdBYphQA8LEy0WM1sDDlr80B6WvqN6ZoUfm/n2rbxvJoLJXuOyzg

      qriL1NmSzJxfd9frMqNLdwroD0ydBHPZ/BoRu6Q8izWNgQHiBS8='
  - secure: ! 'Lk1xETiZMVBUKgMWHlEvL3D8FgeR9CADAMueJK5eQFsD7QSN6ndTH1Yha3mR

      h+2MZkTUEOyXP4jFJRwmBRscxKA92zA+hhMM9Dcn/evD8nwnnTP71Izf9Gjw

      aROoZMu2wtcvdhyjMD5fkttOW2FaBAXhf5u+NCE7KcK8dEYwzHw='
  - secure: ! 'ap/aDotu+CgMrwUheY2n94U6EDQIMolEm6/JSJMv/6+vjYG/8VxRTkZIDW2z

      LpC4LBhUhHYIoO3/gSba7SSOWi50lX1Ro8KeAgEvglo5qCmufnMJa6r8SnME

      eANHK2/8YpaG4y5V+cW6MBWSkqqNQpkpP1O8rLyYre5eeaBm4pE='
  - secure: ! 'lneMTW3JLqkMCfsgK0RnoJp87QlX5GhsNFi949AtaKKcyvHR636gdsbzrXYy

      deiKMjzmjVpwN7PqNUxcNNrMCh7Et/crL+oLOgVr6SHNDAjvD8xBA1DBn+2C

      ectNYnS2JqsRLllrD9tskkqJ4uLezMtR3QxgBqvaybQr2J+uUA4='
  - secure: ! 'qfDxVugl6KFRbAnaI/vGNISgmxfM/3Z3cEg3rhRaDaX1it2jwOFJUmfH5mfL

      g0Sk35soRB/txLCMp4sDj4r7oXu3nTov2FsgAPsol57Ud2T1al3+TMQATUCJ

      717kdi16tK8jq5JYy8q7VPbitG7Cmz0W7LcEiLtTJx0hhRbfBJE='
  - secure: ! 'sR00xdcn9/g0ox/n1L2/ZqzlGOJgAM9JHTfAqB2GF6YRfTidUsUbpCawTJ7K

      ALtOazWIV7IB6HCIT8ULffHAAUjz5yhRPnx/6eYPf6YiL699mJYNHLgELCLW

      6ikaX7DcW+SGwaO/FgQQP9ARBPNC1Js7KWB/hKjNFbYa8nQzYYc='
  - secure: ! 'UJ29GgDguILg/76AtWR20jgfFJTbAZydenUnSONXZrKlZDGF/TWhazHu235g

      IMsLhWuTOxGBcGYncIOX68gpESVhp26s6Aw1yXQsA794TTyUxFiSq1ezQqO4

      AyybNEN1HwDuKb5AQNJUE6II/K6bIHt5a3Y3CphL3Tz1KWRgWzA='
  - secure: ! 'qcFc1pzkZIHgaFbfSAtCrMurgHp/dhYu1qP2gXPc2omsrVE63Ip+uHDE9cJw

      GtbyQRAPERFBrRW0f4cpujdllRST+ALbMznH9ZWcx2tJ9xWWfdLAxeON6XNE

      Tn41WdvohEJOwG0IH16N68pRR00QnMjaaJ7So72AnpglPj3j/qY='
  - secure: ! 'z45+qgWXAQYQIyGz4kv5lCNEXXxeZyHSASJEXncMQYZE6O7xnP12OpIPBE4r

      cxglWT/K/7DagjHBIQYjBZKj8sEFblwV+MIxh75BL7eThAeYRHloDkA1FPFz

      cK+YhH/cijQNXJzRoB1vef05WuFCNANmSXDZ4PL8h4dRD4KIgPQ='
  - secure: ! 'myFzE5z4qdoxwizGl3XhkLnbQL4iwPL2i/Nftrx+SmYNNZ3GuWhBvzWy50a7

      lHJ5t+vCQCI4U7nemHwdqIfcgBK4/770cGgJULev85ZEaNv7YJbp+j/VrshB

      gY7UQJHaVABIgOpxTFIss2sugBwaxgqInCsYmzauoG66eTQvnII='
  - secure: ! 'HEso2fVAhlTZc1wLKhfhCbhsNZnYF6ebj2begIjy5gV4r/2O10z0bg1hKeG5

      9tF3Q3yMAF7qseYknvB34Ad2jx52BYaxAmgAqUNoE2ZFS/D6wapriX4nJUhh

      R3hgWB6cn00Rsmx8wxE3Lxcs2sQfUabaYBw6Nl/PzCOOtTiqvX0='
  - secure: ! 'kbaArY1aBZ9dh8v4PgfKdyQC/gY6+f4DYreINBlwLNJZt2Z7Lau7aJZIyclw

      utRjs75tkjDs6rMuflI3ixw/RRLSYxFoTnBMqVuYSrRS24zP0uNbEpFyCNIT

      QSxV4FKSNdyKw5GW0KnnYcwIoOcBaEP84w830J4M9/jpc6yVc0o='
  - secure: ! 'sr1rPef4RLFlKc3Cwnov4VURXMR1DqnKuMRXCMqXBah2seVm7bW93rwUYGpP

      9LBYlRa4DKZABN40jEIVIokj7vVmGcPkN0dwiC/k4H5WENaxsrdwGFlGee/z

      CXqI3FIKhbjhvb9DUva5B2+Q/Vq1ffKehEOjwVkZxOysyosqzNA='
  - secure: ! 'NEggIjTvsYNvS3EUgGh4ExNoKGQrXTR0LRrwow8cprm2HacciafivQ1QtHPY

      RvdsTbltHXYQV3QhYmAfoMQwD0cYnMsn7kUSQNXaaOpzltmrXbCWshxmj67h

      w9fsDMNoXG4wmAuU57oG/4ceeSvQkuL/FzO/yZ2Ix/SMfOXcS40='
