---
language: python
install:
- sudo apt-get install -qq libmemcached-dev
- pip install -r requirements.txt
before_script:
- psql -c 'create database django_canadanewyork;' -U postgres
- python manage.py collectstatic --noinput
script:
- python manage.py test tests
notifications:
  email: false
env:
  global:
  - DJANGO_SETTINGS_MODULE=configs.settings
  - CANADA_TESTRUNNER=True
  - CANADA_ALLOWED_HOST=*
  - CANADA_DEBUG=False
  - CANADA_SENTRY=False
  - CANADA_STORAGE=local
  - CANADA_CACHE=dummy
  - CANADA_CACHE_TEMPLATES=False
  - CANADA_CONSOLE_LOGGING_LEVEL=INFO
  - DATABASE_URL=postgres://postgres@localhost/django_canadanewyork
  - DJANGO_SETTINGS_MODULE=configs.settings
  - SECRET_KEY=not_so_secret
