# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateField(help_text='Used for ordering', verbose_name='Precise Date')),
                ('date_text', models.CharField(blank=True, help_text='If set, will display <strong>instead of</strong> the precise date.', max_length=500, verbose_name='Inprecise Date')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='artists.Artist')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
