# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 15:02
from __future__ import unicode_literals

from django.db import migrations
import libs.ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=libs.ckeditor.fields.CKEditorField(blank=True),
        ),
    ]
