# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 15:10
from __future__ import unicode_literals

import uuid

from django.db import migrations
import libs.slugify.fields


def default_slug():
    return str(uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=libs.slugify.fields.SlugifyField(default=default_slug, max_length=251, populate_from=('artist', 'title'), unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set([('artist', 'title')]),
        ),
    ]
