# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 15:23
from __future__ import unicode_literals

import apps.photos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20160103_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400)),
                ('caption', models.TextField(blank=True, verbose_name='Extra Text')),
                ('image', models.ImageField(max_length=1000, upload_to=apps.photos.models.original_image_path_function, verbose_name='Image File')),
                ('thumbnail_image', models.ImageField(blank=True, editable=False, height_field='thumbnail_image_height', max_length=1000, null=True, upload_to=apps.photos.models.thumbnail_image_path_function, width_field='thumbnail_image_width')),
                ('large_image', models.ImageField(blank=True, editable=False, height_field='large_image_height', max_length=1000, null=True, upload_to=apps.photos.models.large_image_path_function, width_field='large_image_width')),
                ('thumbnail_image_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('thumbnail_image_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('large_image_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('large_image_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='books.Book')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
    ]
