# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 14:03
from __future__ import unicode_literals

import apps.books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookphoto',
            name='icon_image',
            field=models.ImageField(blank=True, editable=False, height_field='icon_image_height', max_length=1000, null=True, upload_to=apps.books.models.icon_image_path_function, width_field='icon_image_width'),
        ),
        migrations.AddField(
            model_name='bookphoto',
            name='icon_image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='bookphoto',
            name='icon_image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
