# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20160108_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.PositiveSmallIntegerField(help_text='If blank, will not show buy button.', null=True),
        ),
    ]
