# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 19:24
from __future__ import unicode_literals

from functools import partial


def _preset_photo_order(content_object_name, apps, schema_editor):
    '''
    Give every Photo a unique position, in relation to it's parent
    object.

    Modified from http://django-admin-sortable2.readthedocs.org/en/latest/usage.html#initial-data
    '''
    ContentObjectPhoto = apps.get_model(*content_object_name)
    ContentObject = ContentObjectPhoto.content_object.field.related_model
    for content_object in ContentObject.objects.all():
        position = 0
        for content_object_photo in ContentObjectPhoto.objects.filter(content_object=content_object):
            content_object_photo.position = position
            content_object_photo.save(update_fields=['position'])
            position += 1


preset_photo_order = lambda name: partial(_preset_photo_order, name)
